
export const drink1 = [
    {
        id: 0,
        name: "Classic Cappuccino",
        price: 4.35,
        image: require("@/assets/images/classic-cappuccino.png"),
        ratings: 4.8,
        description: "A bold shot of espresso meets perfectly steamed milk, crowned with thick, frothy foam. The result? A velvety, full-bodied experience that balances rich intensity with creamy contrast—both invigorating and indulgent in every sip.",
        subTitle: "Fortified with Tradition",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 1,
        name: "Caramel Cappuccino",
        price: 4.55,
        image: require("@/assets/images/caramel-cappuccino.png"),
        ratings: 4.6,
        description: "Deep espresso entwines with golden caramel, yielding a drink both smooth and sumptuous. The buttery sweetness melds effortlessly with creamy milk, creating an experience that lingers—a delightful contrast of smokiness and warmth.",
        subTitle: "Drenched in Golden Bliss",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 2,
        name: "Vanilla Cappuccino",
        price: 4.55,
        image: require("@/assets/images/vanilla-cappuccino.png"),
        ratings: 4.5,
        description: "A comforting infusion of robust espresso and delicate vanilla, where warmth and sweetness intertwine. Its creamy aroma and gentle finish invite one into an elegant moment, simple yet refined.",
        subTitle: "Enlightened with Velvet",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 3,
        name: "HazeInut Cappuccino",
        price: 4.50,
        image: require("@/assets/images/hazeinut-cappuccino.png"),
        ratings: 4.7,
        description: "The rich embrace of roasted hazelnut meets the bold presence of espresso, weaving a tapestry of flavor. The nutty depth enhances the coffee’s natural warmth, mingling with smooth milk for an experience both indulgent and satisfying.",
        subTitle: "Embedded with taste",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 4,
        name: "Mocha Cappuccino",
        price: 4.75,
        image: require("@/assets/images/mocha-cappuccino.png"),
        ratings: 4.9,
        description: "A rich fusion of espresso and chocolate, where deep coffee notes meld with bittersweet cocoa for an irresistible balance of energy and indulgence. Velvety milk softens the bold flavors, creating a smooth, dessert-like experience that lingers in every sip. A perfect companion for both morning rituals and mid-day escapes.",
        subTitle: "Fused with flavor",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 5,
        name: "Chocolate Cappuccino",
        price: 4.75,
        image: require("@/assets/images/chocolate-cappuccino.png"),
        ratings: 4.8,
        description: "A rich blend of espresso and smooth chocolate, this cappuccino balances bold intensity with gentle sweetness. The cocoa enhances the experience, creating a comforting and refined indulgence—perfect for a cozy moment of relaxation.",
        subTitle: "Wrapped with Richness",
        isFavorite: false,
        isCart: false,
    }
];
export const drink2 = [
    {
        id: 0,
        name: "Cafè Latte",
        price: 4.25,
        image: require("@/assets/images/cafe-latte.png"),
        ratings: 4.3,
        description: "A rich, full-bodied espresso blended with perfectly steamed milk, creating a velvety texture and smooth finish. Its creamy balance allows the coffee’s natural depth to shine through, offering a comforting and refined experience with every sip.",
        subTitle: "Classic Milk Coffee",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 1,
        name: "Vanilla Latte",
        price: 4.75,
        image: require("@/assets/images/vanilla-latte.png"),
        ratings: 4.5,
        description: "A smooth fusion of bold espresso and creamy vanilla-infused steamed milk, creating a luscious balance of sweetness and depth. The rich aroma enhances the experience, making each sip both comforting and indulgent.",
        subTitle: "Sweet & Smooth",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 2,
        name: "Caramel Brulée Latte",
        price: 5.25,
        image: require("@/assets/images/caramel-bruless-latte.png"),
        ratings: 4.6,
        description: "A decadent blend of bold espresso and creamy milk, infused with rich caramel and finished with a crisp layer of caramelized sugar. The deep, buttery sweetness enhances the coffee’s intensity, creating a luxurious and indulgent experience with every sip.",
        subTitle: "Indulgent Caramel Bliss",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 3,
        name: "Pumpkin Spice Latte",
        price: 5.45,
        image: require("@/assets/images/pumpkin-spice-latte.png"),
        ratings: 4.7,
        description: "A comforting blend of rich espresso and smooth milk, infused with warm autumn spices and velvety pumpkin flavor. The subtle sweetness and aromatic depth create a cozy, seasonal indulgence that’s both bold and soothing.",
        subTitle: "Autumn Favorite",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 4,
        name: "Iced Lavender Oatmilk Latte",
        price: 5.75,
        image: require("@/assets/images/iced-lanvender-oatmilk-latte.png"),
        ratings: 4.4,
        description: "A rich combination of bold espresso, velvety chocolate, and refreshing peppermint, finished with a cloud of whipped cream. The contrast of deep cocoa and cool mint creates a perfectly balanced indulgence—both invigorating and comforting.",
        subTitle: "Floral & Creamy",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 5,
        name: "Peppermint Mocha Latte",
        price: 5.55,
        image: require("@/assets/images/peppermint-mocha-latte.png"),
        ratings: 4.6,
        description: "A rich blend of bold espresso, smooth chocolate, and invigorating peppermint, crowned with a swirl of whipped cream. The contrast of deep cocoa and cool mint creates a vibrant, indulgent treat that’s both refreshing and comforting.",
        subTitle: "Minty Chocolate Treat",
        isFavorite: false,
        isCart: false,
    }
];
export const drink3 = [
    {
        id: 0,
        name: "Caffè Americano",
        price: 3.45,
        image: require("@/assets/images/caffe-americano.png"),
        ratings: 4.5,
        description: "A bold espresso infused with hot water, balancing its intensity while retaining depth. Aromatic, smooth, and rich, with subtle caramelized undertones and a lasting finish. Perfect black for boldness or with milk for a gentler touch.",
        subTitle: "Smooth & Bold",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 1,
        name: "Iced Caffè Americanos",
        price: 3.65,
        image: require("@/assets/images/iced-caffe-americano.png"),
        ratings: 4.8,
        description: "A chilled twist on the classic Americano, where bold espresso is poured over ice to create a crisp, invigorating experience. The cooling effect enhances the espresso’s depth, making each sip both smooth and refreshing. Perfect for warm days or when you need a revitalizing pick-me-up.",
        subTitle: "Cool & Crisp",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 2,
        name: "Viennese Americano",
        price: 3.75,
        image: require("@/assets/images/viennese-americano.png"),
        ratings: 4.2,
        description: "A refined take on the Americano, enhanced with a swirl of whipped cream that softens its bold edge and adds a velvety richness. The espresso’s deep flavors meld beautifully with the airy texture, creating a smooth, indulgent experience.",
        subTitle: "Rich & Creamy",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 3,
        name: "Decaf Americano",
        price: 3.45,
        image: require("@/assets/images/decaf-americano.png"),
        ratings: 4.1,
        description: "A smooth, caffeine-free take on the classic Americano, delivering its signature boldness without the kick. Deep, rich, and satisfying, it retains the essence of espresso while providing a mellow, relaxed experience.",
        subTitle: "Bold, No Buzz",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 4,
        name: "Americano Misto",
        price: 4.25,
        image: require("@/assets/images/americano-misto.png"),
        ratings: 4.3,
        description: "A harmonious fusion of espresso, hot water, and steamed milk, elevating the classic Americano with a velvety texture. The bold espresso is softened by the reamy richness, resulting in a smooth, balanced sip with a touch of warmth.",
        subTitle: "Smooth & Creamy",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 5,
        name: "Almondmilk Americano",
        price: 4.95,
        image: require("@/assets/images/almondmilk-americano.png"),
        ratings: 4.4,
        description: "A smooth and bold Americano enhanced with almond milk, introducing a subtle nutty sweetness that complements the rich espresso. The result is a balanced, dairy-free alternative with a velvety texture and a warm, toasty finish.",
        subTitle: "Nutty & Bold",
        isFavorite: false,
        isCart: false,
    }
];
export const drink4 = [
    {
        id: 0,
        name: "Espresso Macchiato",
        price: 2.55,
        image: require("@/assets/images/espresso-macchiato.png"),
        ratings: 4.6,
        description: "A bold shot of espresso lightly topped with foamed milk, softening its intensity while maintaining its rich character. The contrast between deep coffee notes and airy froth creates a smooth yet invigorating experience.",
        subTitle: "Bold & Marke",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 1,
        name: "Cortado",
        price: 2.95,
        image: require("@/assets/images/cortado.png"),
        ratings: 4.7,
        description: "A perfectly balanced fusion of espresso and steamed milk, where bold coffee notes meet creamy smoothness. The velvety texture enhances the richness of the brew, delivering a harmonious and satisfying experience in every sip.",
        subTitle: "Balanced & Velvety",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 2,
        name: "Flat White",
        price: 4.25,
        image: require("@/assets/images/flat-white.png"),
        ratings: 4.9,
        description: "A velvety espresso drink crafted with finely textured microfoam milk, delivering a smooth and luxurious sip. The richness of the espresso blends seamlessly with the silky foam, creating a well-balanced and indulgent experience.",
        subTitle: "Smooth & Rich",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 3,
        name: "Caramel Macchiato",
        price: 4.45,
        image: require("@/assets/images/caramel-macchiato.png"),
        ratings: 4.3,
        description: "A rich espresso creation infused with vanilla syrup, steamed milk, and topped with a decadent caramel drizzle. The interplay of bold coffee, creamy sweetness, and silky texture makes each sip indulgent and satisfying.",
        subTitle: "Sweet & Velvety",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 4,
        name: "Caffè Mocha",
        price: 4.15,
        image: require("@/assets/images/caffe-mocha.png"),
        ratings: 4.5,
        description: "A rich espresso blend infused with velvety chocolate, perfectly complemented by steamed milk. Finished with a luscious topping of whipped cream or cocoa powder, this indulgent drink delivers a smooth, decadent coffee experience.",
        subTitle: "Chocolate & Bold",
        isFavorite: false,
        isCart: false,
    },
    {
        id: 5,
        name: "Iced Shaken Espresso",
        price: 3.95,
        image: require("@/assets/images/ice-shaken-espresso.png"),
        ratings: 4.6,
        description: "A vibrant espresso shaken vigorously with ice and sweetener, creating a frothy, chilled texture that enhances its bold flavors. Smooth, refreshing, and invigorating—perfect for an energizing coffee experience.",
        subTitle: "Frothy & Refreshing",
        isFavorite: false,
        isCart: false,
    }
]